### ISSUE TITLE
Testing from lambda

### ISSUE THREAD

**Issue by aarthisankaran** [huksley/serverless-java-micronaut#2]
I get this error: {
  "errorMessage": "Error starting Micronaut container: No bean of type [io.micronaut.jackson.codec.JsonMediaTypeCodec] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing."
}

Would appreciate any help in this regard.

**Comment by aarthisankaran** [comment]
01:01:52.545 [main] INFO i.m.f.a.p.AbstractLambdaContainerHandler - Starting Lambda Container Handler
01:01:52.560 [main] INFO i.m.context.env.DefaultEnvironment - Established active environments: [function]
com.amazonaws.serverless.exceptions.ContainerInitializationException: Error starting Micronaut container: No bean of type [io.micronaut.jackson.codec.JsonMediaTypeCodec] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.initialize(MicronautLambdaContainerHandler.java:191)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.<init>(MicronautLambdaContainerHandler.java:104)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.getAwsProxyHandler(MicronautLambdaContainerHandler.java:133)
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.startRuntimeApiEventLoop(MicronautLambdaRuntime.java:111)
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:76)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.jackson.codec.JsonMediaTypeCodec] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1679)
at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:555)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.initialize(MicronautLambdaContainerHandler.java:183)
... 4 more
Request loop failed with: Error starting Micronaut container: No bean of type [io.micronaut.jackson.codec.JsonMediaTypeCodec] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.

**Comment by huksley** [comment]
Hi, sorry for being late on this, 
If you are invoking from IDE like Intellij IDEA this is usually caused by not enabling annotation processing in the settings. It is disable by default, 
please check out the docs
https://guides.micronaut.io/creating-your-first-micronaut-app/guide/#writingTheApp
